# Generated by Django 5.0.6 on 2024-06-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pubdate', models.DateTimeField()),
                ('author', models.PositiveIntegerField()),
                ('author_realname', models.CharField(db_index=True, max_length=30)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('status', models.PositiveIntegerField()),
            ],
        ),
    ]
