# Generated by Django 5.0.6 on 2024-06-02 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='pubdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
