# Generated by Django 5.0.6 on 2024-06-04 00:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_notice_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pubdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('author_realname', models.CharField(db_index=True, max_length=30)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('status', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
