# Generated by Django 5.0.6 on 2024-06-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_notice_author_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='thumbupcount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
