# Generated by Django 4.2.13 on 2025-11-24 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_thumbup_profile_graduatedesign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graduatedesign",
            name="currentstate",
            field=models.CharField(default="Topic Created", max_length=200),
        ),
        migrations.AlterModelTable(name="graduatedesign", table="cimp_graduatedesign",),
        migrations.CreateModel(
            name="GraduateDesignStep",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("operator_realname", models.CharField(max_length=30)),
                ("actiondate", models.DateTimeField(default=django.utils.timezone.now)),
                ("actionname", models.CharField(max_length=50)),
                ("nextstate", models.CharField(max_length=50)),
                ("submitdata", models.TextField()),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="main.graduatedesign",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "cimp_graduatedesign_step",},
        ),
    ]
